name: CI
env:
  APPLICATION_NAME: "MyApplication"
  GIT_SHA_APP_NAME: "my-app-sha-${{ github.sha }}"

on: 
  push:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: echo "Run of test pipes"
      
      - name: execute few commands
        run: |
          echo "Application name: ${{env.APPLICATION_NAME }}"
          echo "Running test #1"
      
      - name: git clone project
        uses: action/checkout@v1
        with:
          ref: 'main'

      - name: clone result
        run: |
          echo "Repository clone is successful" 
      
      - name: list current directory
        run: ls -la
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
    steps:
      - name: Deploy
        run: echo "Deploy run"
      
      - name: print deploy packages sha
        run: echo "Deploy packages name is  $(git rev-parse --short HEAD)"
